### ISSUE TITLE
biGraph is a misleading name

### ISSUE THREAD

**Issue by andrew-appel** [Salamari/CertiGraph#12]
In conventional mathematical terminology, "bigraph" is short for "bipartite graph".  Within CertiGraph, "biGraph" appears to mean "binary graph", that is, a graph where every nontrivial node has 2 out-edges.   This is unnecessarily confusing.  I suggest you rename the module, and all the relevant files.  Perhaps binGraph and demo/mark_bin.c, et cetera.

**Comment by txyyss** [comment]
It is done now.
