### ISSUE TITLE
"mark" demo issues

### ISSUE THREAD

**Issue by andrew-appel** [Salamari/CertiGraph#9]
The "mark" demo, in the mark subdirectory, 
1.  Needs a Makefile and a _CoqProject
2. Should build independently of the main repo, just as the "demo" subdirectory does
3. Should probably be merged into the demo directory, which would then have two .c files, one a tree-traversal and one a depth-first-search

**Comment by txyyss** [comment]
The mark demo is the first application of the CertiGraph library. So now it is built within the repo. I will move it to the demo directory so the two demos can share the same Makefile and _CoqProject.

**Comment by txyyss** [comment]
It is done now.
